---
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.23.6
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Run unit tests
        run: make tests
      - name: Run integration tests
        run: make integration-tests
      - name: Release
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          version: '~> v2'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
